# Generated by Django 6.1.1 on 2026-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "productId",
                    models.PositiveIntegerField(
                        help_text="unique ID of product",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "productName",
                    models.CharField(
                        blank=True,
                        help_text="Name of product",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="sku of product",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="color of product",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="size of product",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(default=True, help_text="is active product"),
                ),
            ],
        ),
    ]
