# Generated by Django 6.1.1 on 2026-10-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["productId"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="productId",
            field=models.BigAutoField(
                help_text="unique ID of product", primary_key=True, serialize=False
            ),
        ),
    ]
