# Generated by Django 6.1.1 on 2026-10-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagedProduct",
            fields=[
                (
                    "product_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("product_data", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
